[package]
name = "ChainReactionFun"
version = "1.0.0"
authors = []

[addresses]
chain_reaction = "0x987"
chain_reaction_fun = "0x567"
std = "0x1"
aptos_framework = "0x1"
aptos_token = "0x3"
#"03b1ad6b36dc54d1a73c1beb10159b1c6adfdbef736fa51c558d97099664c17c"
public_key = "0x2c6d33bd68066e591671c361a22cd4c02ed5c436939c163ac6c723bc3857b4b0"
#Constants for test addresses
PLAYER1 = "0x123"
PLAYER2 = "0x456"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
