[package]
name = "ChainReactionFun"
version = "1.0.0"
authors = []

[addresses]
chain_reaction = "03b1ad6b36dc54d1a73c1beb10159b1c6adfdbef736fa51c558d97099664c17c"
chain_reaction_fun = "03b1ad6b36dc54d1a73c1beb10159b1c6adfdbef736fa51c558d97099664c17c"
public_key = "8a66ebbc8cd1bd6424c8a9fc1e8d7333e9cd5ebfaad6e1e9d178406c383d7ba3"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
